apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-2048-argocd-config
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/kodermon/app-2048-argocd-helm-terraform.git
    targetRevision: HEAD
    path: app-2048
  destination:
    server: https://kubernetes.default.svc
    namespace: app-2048

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true